module CameraDemo {
    enum CameraControlOutputReqType { OutputGet, OutputSet, OutputUpdate };
    struct CameraControlOutputRequest {
        uint16 messageId;
        CameraControlOutputReqType reqType;
        float angularPositionPan;
        float angularPositionTilt;
    };
    struct CameraControlOutputResponse {
        float angularPositionPan;
        float angularPositionTilt;
    };
};
