module CameraDemo {
    enum OrientationOutputReqType { OutputGet, OutputSet, OutputUpdate };
    struct OrientationOutputRequest {
        uint16 messageId;
        OrientationOutputReqType reqType;
        float angularPosition;
    };
    struct OrientationOutputResponse {
        float angularPosition;
    };
};
