module Orion {
	struct Command {
		@value(208)
		uint8 sync0;

		@value(13)
		uint8 sync1;

		@value(1)
		uint8 id;

		@value(7)
		uint8 length;

		int16 pan;

		// Expressed in 1/1000th radians units
		@range(min = -1396, max = 733)
		int16 tilt;

		@value(80)
		uint8 mode;

		@value(0)
		uint8 stabilized;

		@value(0)
		uint8 impulse;

		uint16 checksum;
	};

	struct CameraState {
		@value(208)
		uint8 sync0;

		@value(13)
		uint8 sync1;

		@value(97)
		uint8 id;

		@value(5)
		uint8 length;

		int16 zoom;

		int16 focus;

		@value(0)
		uint8 index;

		uint16 checksum;
	};

	struct VideoSettings {
		@value(208)
		uint8 sync0;

		@value(13)
		uint8 sync1;

		@value(98)
		uint8 id;

		@value(14)
		uint8 length;

		uint8 destIp[4];

		uint16 port;

		@value(0)
		uint32 bitrate;

		@value(0)
		int8 ttl;

		@value(0)
		uint8 streamType;

		@value(0)
		uint8 mjpegQuality;

		@value(0)
		uint8 saveSettingsAndTsPacketCount;

		uint16 checksum;
	};

	struct AptinaSettings {
		@value(208)
		uint8 sync0;

		@value(13)
		uint8 sync1;

		@value(104)
		uint8 id;

		@value(15)
		uint8 length;

		@value(0)
		uint8 index;

		uint16 minExposure;

		uint16 maxExposure;

		uint16 minGain;

		uint16 maxGain;

		int8 brightness;

		int8 contrast;

		int8 saturation;

		uint8 sharpness;

		uint8 debugEnable;

		int8 hue;

		uint16 checksum;
	};

	struct Limits {
		@value(208)
		uint8 sync0;

		@value(13)
		uint8 sync1;

		@value(34)
		uint8 id;

		@value(0)
		uint8 length;

		uint16 checksum;
	};
};
