module Orion {
	struct Command {
		@value(208)
		uint8 sync0;

		@value(13)
		uint8 sync1;

		@value(1)
		uint8 id;

		@value(7)
		uint8 length;

		int16 pan;

		int16 tilt;

		@value(80)
		uint8 mode;

		@value(0)
		uint8 stabilized;

		@value(0)
		uint8 impulse;

		uint16 checksum;
	};

	struct VideoSettings {
		@value(208)
		uint8 sync0;

		@value(13)
		uint8 sync1;

		@value(98)
		uint8 id;

		uint8 destIp[4];

		uint16 port;

		@value(0)
		uint32 bitrate;

		@value(0)
		int8 ttl;

		@value(0)
		uint8 streamType;

		@value(0)
		uint8 mjpegQuality;

		@value(0)
		uint8 saveSettingsAndTsPacketCount;

		uint16 checksum;
	};
};
