// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: challenge_rpc.proto

#include "challenge_rpc.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
static constexpr ::PROTOBUF_NAMESPACE_ID::Metadata* file_level_metadata_challenge_5frpc_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_challenge_5frpc_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_challenge_5frpc_2eproto = nullptr;
const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_challenge_5frpc_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_challenge_5frpc_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\023challenge_rpc.proto\032\036google/protobuf/w"
  "rappers.proto2Q\n\010Encrypt1\022E\n\007Encrypt\022\033.g"
  "oogle.protobuf.BytesValue\032\033.google.proto"
  "buf.BytesValue\"\0002Q\n\010Encrypt2\022E\n\007Encrypt\022"
  "\033.google.protobuf.BytesValue\032\033.google.pr"
  "otobuf.BytesValue\"\000b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_challenge_5frpc_2eproto_deps[1] = {
  &::descriptor_table_google_2fprotobuf_2fwrappers_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_challenge_5frpc_2eproto_sccs[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_challenge_5frpc_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_challenge_5frpc_2eproto = {
  false, false, descriptor_table_protodef_challenge_5frpc_2eproto, "challenge_rpc.proto", 227,
  &descriptor_table_challenge_5frpc_2eproto_once, descriptor_table_challenge_5frpc_2eproto_sccs, descriptor_table_challenge_5frpc_2eproto_deps, 0, 1,
  schemas, file_default_instances, TableStruct_challenge_5frpc_2eproto::offsets,
  file_level_metadata_challenge_5frpc_2eproto, 0, file_level_enum_descriptors_challenge_5frpc_2eproto, file_level_service_descriptors_challenge_5frpc_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_challenge_5frpc_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_challenge_5frpc_2eproto)), true);

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
