module NestedTypes {
  struct Foo {
    int32 a, b, c;
  };
  struct Bar {
    double x, y, z;
  };
  struct OuterStruct {
    Foo foo;
    Bar bar;
  };
  enum DayOfWeek { Monday, Tuesday, Wednesday, Thursday, Friday };
  union OuterUnion switch (DayOfWeek) {
    case Monday:
    case Tuesday:
    case Wednesday:
      Foo foo;
    case Thursday:
    case Friday:
      Bar bar;
  };
  union ScopedOuterUnion switch (DayOfWeek) {
    case DayOfWeek::Monday:
    case DayOfWeek::Tuesday:
    case DayOfWeek::Wednesday:
      Foo foo;
    case DayOfWeek::Thursday:
    case DayOfWeek::Friday:
      Bar bar;
  };
};
